export { default as MainTab } from "./MainTab"
export { default as NotificationTab } from "./NotificationTab"
export { default as ProfileTab } from "./ProfileTab"
export { default as SearchTab } from "./SearchTab"
export { default as UploadTab } from "./UploadTab"
